# Generated by Django 6.0.1 on 2026-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_description_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pickem_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
